/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AttachmentsRouteImport } from './routes/attachments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminModulesRouteImport } from './routes/admin/modules'
import { Route as AdminChecklistsRouteImport } from './routes/admin/checklists'
import { Route as AdminCasesRouteImport } from './routes/admin/cases'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAiInsightsRouteImport } from './routes/admin/ai-insights'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentsRoute = AttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/admin/modules',
  path: '/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChecklistsRoute = AdminChecklistsRouteImport.update({
  id: '/admin/checklists',
  path: '/admin/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/admin/cases',
  path: '/admin/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiInsightsRoute = AdminAiInsightsRouteImport.update({
  id: '/admin/ai-insights',
  path: '/admin/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attachments': typeof AttachmentsRoute
  '/cases': typeof CasesRoute
  '/chat': typeof ChatRoute
  '/checklists': typeof ChecklistsRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/admin/ai-insights': typeof AdminAiInsightsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attachments': typeof AttachmentsRoute
  '/cases': typeof CasesRoute
  '/chat': typeof ChatRoute
  '/checklists': typeof ChecklistsRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/admin/ai-insights': typeof AdminAiInsightsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attachments': typeof AttachmentsRoute
  '/cases': typeof CasesRoute
  '/chat': typeof ChatRoute
  '/checklists': typeof ChecklistsRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/admin/ai-insights': typeof AdminAiInsightsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attachments'
    | '/cases'
    | '/chat'
    | '/checklists'
    | '/contacts'
    | '/login'
    | '/settings'
    | '/tracking'
    | '/admin/ai-insights'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/checklists'
    | '/admin/modules'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attachments'
    | '/cases'
    | '/chat'
    | '/checklists'
    | '/contacts'
    | '/login'
    | '/settings'
    | '/tracking'
    | '/admin/ai-insights'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/checklists'
    | '/admin/modules'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/attachments'
    | '/cases'
    | '/chat'
    | '/checklists'
    | '/contacts'
    | '/login'
    | '/settings'
    | '/tracking'
    | '/admin/ai-insights'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/checklists'
    | '/admin/modules'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttachmentsRoute: typeof AttachmentsRoute
  CasesRoute: typeof CasesRoute
  ChatRoute: typeof ChatRoute
  ChecklistsRoute: typeof ChecklistsRoute
  ContactsRoute: typeof ContactsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
  AdminAiInsightsRoute: typeof AdminAiInsightsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminChecklistsRoute: typeof AdminChecklistsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachments': {
      id: '/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklists': {
      id: '/admin/checklists'
      path: '/admin/checklists'
      fullPath: '/admin/checklists'
      preLoaderRoute: typeof AdminChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/admin/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-insights': {
      id: '/admin/ai-insights'
      path: '/admin/ai-insights'
      fullPath: '/admin/ai-insights'
      preLoaderRoute: typeof AdminAiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttachmentsRoute: AttachmentsRoute,
  CasesRoute: CasesRoute,
  ChatRoute: ChatRoute,
  ChecklistsRoute: ChecklistsRoute,
  ContactsRoute: ContactsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
  AdminAiInsightsRoute: AdminAiInsightsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminChecklistsRoute: AdminChecklistsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
